---
- name: "Copy {{ module }} policy module"
  template:
    src: "{{ module }}.cil.j2"
    dest: "{{ semodule_dir | default(semodule_default_dir) }}/{{ module }}.cil"
    owner: root
    group: root
    mode: '0644'
  register: selinux_module

- name: "Install {{ module }} policy module" # noqa no-handler
  command:
    cmd: "semodule -i {{ semodule_dir | default(semodule_default_dir) }}/{{ module }}.cil"
  when: selinux_module.changed
